baseURL = "https://www.ivpn.net" 
title = "IVPN"
theme = "ivpn-v3"
paginate = 8
summaryLength = 35
disableKinds = ["sitemap", "taxonomy"]
pygmentsUseClasses=true
pygmentsCodefencesGuessSyntax=true
pygmentsCodefences=true
pygmentsStyle="monokai"
pygmentsOptions="noclasses=false"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageCode = "en"
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
  [languages.es]
    languageCode = "es"
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 2

[markup.goldmark.renderer]
    unsafe= true

[outputs]
    home = ["HTML"]
    section = ["JSON", "HTML", "RSS"]

[params]
    environment = "development"    
    images = ["/images-static/uploads/og_1200-627.png"]
    cdnUrl = ""
    matomoEnabled = false
    matomoUrl = "https://stats.ivpn.net"
    matomoSiteId = 1

[taxonomies]
  category = "categories"
  tag = "tags"
  authors = "authors"

[permalinks]
  categories = "blog/categories/:slug/"
  tags = "blog/tags/:slug/"
  authors = "blog/authors/:slug/"

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
  name = "categories"
  weight = 90
  [[related.indices]]
  name = "tags"
  weight = 40
  [[related.indices]]
  name  = "date"
  weight = 60
  pattern = "200601"